# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  agent: zhaoxiaotong

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '6.0.x'


steps:
- script: dotnet restore
  displayName: 'Nuget restore'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'
- script: dotnet test
  displayName: 'UnitTest'
- script: dotnet publish --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
  displayName: 'Publish'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()